//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDL.AnyCodes.SmsMutiSendService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsMutiSendService.SmsMultiSendServiceSoap")]
    public interface SmsMultiSendServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 mobiles 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAliTplSMS", ReplyAction="*")]
        ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponse SendAliTplSMS(ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAliTplSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponse> SendAliTplSMSAsync(ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendAliTplSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendAliTplSMS", Namespace="http://tempuri.org/", Order=0)]
        public ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequestBody Body;
        
        public SendAliTplSMSRequest() {
        }
        
        public SendAliTplSMSRequest(ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendAliTplSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tplid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sign;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string param;
        
        public SendAliTplSMSRequestBody() {
        }
        
        public SendAliTplSMSRequestBody(string mobiles, string tplid, string sign, string param) {
            this.mobiles = mobiles;
            this.tplid = tplid;
            this.sign = sign;
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendAliTplSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendAliTplSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponseBody Body;
        
        public SendAliTplSMSResponse() {
        }
        
        public SendAliTplSMSResponse(ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendAliTplSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendAliTplSMSResult;
        
        public SendAliTplSMSResponseBody() {
        }
        
        public SendAliTplSMSResponseBody(string SendAliTplSMSResult) {
            this.SendAliTplSMSResult = SendAliTplSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsMultiSendServiceSoapChannel : ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsMultiSendServiceSoapClient : System.ServiceModel.ClientBase<ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap>, ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap {
        
        public SmsMultiSendServiceSoapClient() {
        }
        
        public SmsMultiSendServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsMultiSendServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsMultiSendServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsMultiSendServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponse ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap.SendAliTplSMS(ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest request) {
            return base.Channel.SendAliTplSMS(request);
        }
        
        public string SendAliTplSMS(string mobiles, string tplid, string sign, string param) {
            ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest inValue = new ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest();
            inValue.Body = new ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequestBody();
            inValue.Body.mobiles = mobiles;
            inValue.Body.tplid = tplid;
            inValue.Body.sign = sign;
            inValue.Body.param = param;
            ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponse retVal = ((ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap)(this)).SendAliTplSMS(inValue);
            return retVal.Body.SendAliTplSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponse> ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap.SendAliTplSMSAsync(ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest request) {
            return base.Channel.SendAliTplSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSResponse> SendAliTplSMSAsync(string mobiles, string tplid, string sign, string param) {
            ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest inValue = new ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequest();
            inValue.Body = new ZDL.AnyCodes.SmsMutiSendService.SendAliTplSMSRequestBody();
            inValue.Body.mobiles = mobiles;
            inValue.Body.tplid = tplid;
            inValue.Body.sign = sign;
            inValue.Body.param = param;
            return ((ZDL.AnyCodes.SmsMutiSendService.SmsMultiSendServiceSoap)(this)).SendAliTplSMSAsync(inValue);
        }
    }
}
