//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDL.AnyCodes.FilterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FilterService.FilterServiceSoap")]
    public interface FilterServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 content 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterUserData", ReplyAction="*")]
        ZDL.AnyCodes.FilterService.FilterUserDataResponse FilterUserData(ZDL.AnyCodes.FilterService.FilterUserDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilterUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<ZDL.AnyCodes.FilterService.FilterUserDataResponse> FilterUserDataAsync(ZDL.AnyCodes.FilterService.FilterUserDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWords", ReplyAction="*")]
        void UpdateWords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWords", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateWordsAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilterUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterUserData", Namespace="http://tempuri.org/", Order=0)]
        public ZDL.AnyCodes.FilterService.FilterUserDataRequestBody Body;
        
        public FilterUserDataRequest() {
        }
        
        public FilterUserDataRequest(ZDL.AnyCodes.FilterService.FilterUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilterUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string content;
        
        public FilterUserDataRequestBody() {
        }
        
        public FilterUserDataRequestBody(string content) {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilterUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilterUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZDL.AnyCodes.FilterService.FilterUserDataResponseBody Body;
        
        public FilterUserDataResponse() {
        }
        
        public FilterUserDataResponse(ZDL.AnyCodes.FilterService.FilterUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilterUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FilterUserDataResult;
        
        public FilterUserDataResponseBody() {
        }
        
        public FilterUserDataResponseBody(string FilterUserDataResult) {
            this.FilterUserDataResult = FilterUserDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilterServiceSoapChannel : ZDL.AnyCodes.FilterService.FilterServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilterServiceSoapClient : System.ServiceModel.ClientBase<ZDL.AnyCodes.FilterService.FilterServiceSoap>, ZDL.AnyCodes.FilterService.FilterServiceSoap {
        
        public FilterServiceSoapClient() {
        }
        
        public FilterServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilterServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilterServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilterServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZDL.AnyCodes.FilterService.FilterUserDataResponse ZDL.AnyCodes.FilterService.FilterServiceSoap.FilterUserData(ZDL.AnyCodes.FilterService.FilterUserDataRequest request) {
            return base.Channel.FilterUserData(request);
        }
        
        public string FilterUserData(string content) {
            ZDL.AnyCodes.FilterService.FilterUserDataRequest inValue = new ZDL.AnyCodes.FilterService.FilterUserDataRequest();
            inValue.Body = new ZDL.AnyCodes.FilterService.FilterUserDataRequestBody();
            inValue.Body.content = content;
            ZDL.AnyCodes.FilterService.FilterUserDataResponse retVal = ((ZDL.AnyCodes.FilterService.FilterServiceSoap)(this)).FilterUserData(inValue);
            return retVal.Body.FilterUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZDL.AnyCodes.FilterService.FilterUserDataResponse> ZDL.AnyCodes.FilterService.FilterServiceSoap.FilterUserDataAsync(ZDL.AnyCodes.FilterService.FilterUserDataRequest request) {
            return base.Channel.FilterUserDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZDL.AnyCodes.FilterService.FilterUserDataResponse> FilterUserDataAsync(string content) {
            ZDL.AnyCodes.FilterService.FilterUserDataRequest inValue = new ZDL.AnyCodes.FilterService.FilterUserDataRequest();
            inValue.Body = new ZDL.AnyCodes.FilterService.FilterUserDataRequestBody();
            inValue.Body.content = content;
            return ((ZDL.AnyCodes.FilterService.FilterServiceSoap)(this)).FilterUserDataAsync(inValue);
        }
        
        public void UpdateWords() {
            base.Channel.UpdateWords();
        }
        
        public System.Threading.Tasks.Task UpdateWordsAsync() {
            return base.Channel.UpdateWordsAsync();
        }
    }
}
